import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import styles from "../styles/Home.module.css";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div className={styles.hero}>
                    <div style={{color: "white"}}>
                        <Header />
                    </div>
                    <div className={styles["hero-name"]}>Kat Conley</div>
                </div>
            </main>

            <footer className={styles.footer}>
                <a href="" target="_blank" rel="noopener noreferrer">IMDB </a>
                <a href="" target="_blank" rel="noopener noreferrer">Facebook </a>
                <a href="" target="_blank" rel="noopener noreferrer">Instagram </a>
                <a href="" target="_blank" rel="noopener noreferrer">YouTube</a>
                <a href="" target="_blank" rel="noopener noreferrer">Twitter </a>
                {/* <a href="https://www.gocalavera.com/" target="_blank" rel="noopener noreferrer">
                    Powered by Calavera
                </a> */}
            </footer>
        </div>
    );
}
